devops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ops/', include('ops.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^loginsite/', include('loginsite.urls')),
    # url(r'', views.welcome),
    url(r'^captcha', include('captcha.urls')),
    url(r'^quickstart/', include('quickstart.urls')),
]

loginsite/urls.py
from django.conf.urls import url
from . import views
app_name = 'loginsite'


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^logout/', views.logout, name='logout'),
    url('^refresh/', views.captcha_refresh, name='captcha_refresh'),
]

ops/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'',views.index),
]

loginsite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your models here.
from django.db import models
class User(models.Model):
    gender_choice = (
        ('male', 'man'),
        ('female', 'woman'),
    )
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256, blank=False, null=False)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=12, choices=gender_choice, default='male')
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'userinfo'
        ordering = ['-c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'
        indexes = [
            models.Index(fields=['c_time'], name='create_time'),
            models.Index(fields=['name', 'email'], name='idx_name_email'),
        ]

loginsite/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField
class UserForm(forms.Form):
    username = forms.CharField(label="username", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField()
    remember = forms.BooleanField(label='remember me', required=False)


class RegisterForm(forms.Form):
    gender = (
        ('male', "man"),
        ('female', "woman"),
    )
    username = forms.CharField(label="username", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="password", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="confirm", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="email", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='gender', choices=gender)
    captcha = CaptchaField(label='valide code')

loginsite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import User
from django.shortcuts import render, redirect, render_to_response
from django.http import JsonResponse, Http404, HttpResponse, HttpResponseRedirect
from django.db import models
from django import forms
from .forms import UserForm, RegisterForm
import hashlib
from captcha.models import CaptchaStore
import json

def hash_code(s, salt='mysite'):  # 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()

def captcha_image_url(key):
    return '/captchaimage/{0}/'.format(key)

def captcha_refresh(request):
    if not request.is_ajax():
        raise Http404
    new_key = CaptchaStore.generate_key()
    to_json_response = {
        'key': new_key,
        'image_url': captcha_image_url(new_key),
    }
    return HttpResponse(json.dumps(to_json_response), content_type='application/json')

    # Create your views here.
def index(request):
    # return render(request, 'base.html')
    # for k, v in request.session.items():
    #     print k, v
    # print dir(request.session)
    # print dir(request.session.get_expiry_date)
    # print request.session.get_expiry_date()
    # print request.session.get_expiry_age()
    return render(request, 'loginsite/index.html')

def logout(request):
    if not request.session.get('is_login', None):
        return redirect('/loginsite/login')
    request.session.flush()
    return redirect('/loginsite/index')

def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("/loginsite/index/")
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_username = User.objects.filter(name=username)
                if same_username:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'loginsite/register.html', locals())
                same_email_user = User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'login/register.html', locals())
                new_user = User.objects.create()
                new_user.name = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                return redirect('/loginsite/login/')
    register_form = RegisterForm()
    return render(request, 'loginsite/register.html', locals())

def login(request):
    # return render(request, 'loginsite/login.html')
    # beginSession_time = time.time()
    if request.session.get('is_login', None):
        return redirect('/loginsite/index/')
        # endSession_time = time.time()
        # print endSession_time - beginSession_time
    if request.method == 'POST':
        loginForm = UserForm(request.POST)

        # username = request.POST.get('username')
        # password = request.POST.get('password')
        message = '所有字段都必须填写！'
        if loginForm.is_valid():
            username = loginForm.cleaned_data['username']
            password = loginForm.cleaned_data['password']
            remember = loginForm.cleaned_data['remember']
        # if username and password:
        #     username = username.strip()
        #     password = password.strip()
            try:
                # beginUsertime = time.time()
                user = User.objects.get(name=username)
                # endUsertime = time.time()
                # print endUsertime - beginUsertime
                if user.password == hash_code(password):
                    if not remember:
                        request.session.set_expiry(1800)
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return redirect('/loginsite/index/')
                else:
                    message = 'password wrong!!'
            except:
                message = "用户名不存在！"
        else:
            message = '请输入有效的登录信息'

        return render(request, 'loginsite/login.html', locals())
    loginForm = UserForm()
    return render(request, 'loginsite/login.html', locals())

loginsite/templates/loginsite/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    {% if request.session.is_login %}
    <h1>你好,{{ request.session.user_name }}！欢迎回来！</h1>
    {% else %}
    <h1>你尚未登录，只能访问公开内容！</h1>
    {% endif %}
{% endblock %}

loginsite/templates/loginsite/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} 登录 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">

          <form class='form-login' action="{% url 'loginsite:login' %}" method="post">
              {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎登录</h2>
              <div class="form-group">
                  {{ loginForm.username.label_tag }}
                  {{ loginForm.username }}
              </div>
              <div class="form-group">
                  {{ loginForm.password.label_tag }}
                  {{ loginForm.password }}
              </div>
              <div class="form-group">
                  {{ loginForm.captcha.errors }}
                  {{ loginForm.captcha.label_tag }}
                  {{ loginForm.captcha }}
              </div>
              <div class="form-group">
                  {{ loginForm.remember.label_tag }}
                  {{ loginForm.remember }}
              </div>
              <!--{{ loginForm }}-->
              <!--<div class="form-group">-->
                <!--<label for="id_username">用户名：</label>-->
                <!--<input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>-->
              <!--</div>-->
              <!--<div class="form-group">-->
                <!--<label for="id_password">密码：</label>-->
                <!--<input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>-->
              <!--</div>-->
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
          </form>
        </div>
    </div> <!-- /container -->
<script>
    $(function(){
        $('.captcha').css({
            'cursor': 'pointer'
        })
    $('.captcha').click(function(){
        $.getJSON('/loginsite/refresh/',
            function(result){
                $('.captcha').attr('src', result['image_url']);
                $('#id_captcha_0').val(result['key']);
            }
        );
    });
    });

</script>
{% endblock %}

loginsite/templates/loginsite/register.html
{% extends 'base.html' %}
{% block title %} 登录 {% endblock %}
{% block content %}
<div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="{% url 'loginsite:register' %}" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}

              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                  {{ register_form.username.label_tag }}
                  {{ register_form.username}}
              </div>
              <div class="form-group">
                  {{ register_form.password1.label_tag }}
                  {{ register_form.password1 }}
              </div>
              <div class="form-group">
                  {{ register_form.password2.label_tag }}
                  {{ register_form.password2 }}
              </div>
              <div class="form-group">
                  {{ register_form.email.label_tag }}
                  {{ register_form.email }}
              </div>
              <div class="form-group">
                  {{ register_form.sex.label_tag }}
                  {{ register_form.sex }}
              </div>
              <div class="form-group">
                  {{ register_form.captcha.errors }}
                  {{ register_form.captcha.label_tag }}
                  {{ register_form.captcha }}
              </div>

              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>

          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}