base/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'login',views.login),
    url(r'welcome',views.welcome),
    url(r'logout',views.logout_view),
    url(r'',views.welcome),
]

devops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ops/', include('ops.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^loginsite/', include('loginsite.urls')),
    # url(r'', views.welcome),
    url(r'^captcha', include('captcha.urls')),
    url(r'^quickstart/', include('quickstart.urls')),
]

loginsite/urls.py
from django.conf.urls import url
from . import views
app_name = 'loginsite'


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^register/', views.register, name='register'),
    url(r'^logout/', views.logout, name='logout'),
    url('^refresh/', views.captcha_refresh, name='captcha_refresh'),
]

ops/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'',views.index),
]

base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    lastLoginTime = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return self.username

base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse,HttpResponseRedirect

from django.shortcuts import render,render_to_response
#from ops.models import User
from django.core import serializers
from django import forms
# from base.models import User
from django.contrib.auth import authenticate,logout
from django.contrib.auth import login as base_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
# Create your views here.
class UserForm(forms.Form):
    username = forms.CharField(label='用户名')
    password = forms.CharField(label='密   码',widget=forms.PasswordInput())
    #last_login = forms.DateTimeField()

def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # print username,password
        user = authenticate(username=username, password=password)
        if user is not None:
            base_login(request, user)
            return render(request, "welcome.html", {'msg': 'welcome to hahah'})
        else:
            return render(request,"login.html",{'loginfail':True})
    #     user = User.objects.all().filter(username=username)
    #         if user:
    #             passwd = User.objects.all().filter(username=username,password=password)
    #             if passwd:
    #                 loginState = True
    #             else:
    #                 loginState = False
    #                 msg = "password wrong"
    #         else:
    #             msg = "user does't exist!"
    #             return HttpResponse(msg)
    #         if loginState:
    #             return HttpResponseRedirect("/base/welcome/")
    #         else:
    #             return HttpResponse(msg)
    else:
        return render(request, "login.html")
        #return HttpResponse("Unknown option")

def logout_view(request):
    logout(request)
    return render(request, "login.html")

def ensure_login(request):
    if not request.user.is_authenticated:
        return render(request, "login.html")

@login_required(login_url='/base/login/')
@permission_required('base.welcome', login_url='/base/login/')
def welcome(request):
    return render(request, "welcome.html", {'msg': 'welcome'})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %} base {% endblock %}</title>

    <!-- Bootstrap -->
      <!--{% load static %}-->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"> </script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
      {% block css %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mysite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'loginsite:index' %}">主页</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.session.is_login %}
                <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
                <li><a href="/loginsite/logout/">登出</a></li>
            {% else %}
                <li><a href="/loginsite/login/">登录</a></li>
                <li><a href="/loginsite/register/">注册</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block content %} {% endblock %}


  </body>
</html>